# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: sqlite3
  database: db/development.sqlite3.db

test:
  adapter: sqlite3
  database: db/test.sqlite3.db

production:
  adapter: mysql
  database: viborhostingaru
  username: viborhostingaru
  password: kProject
  host: localhost
  
